export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FIREBASE_LOADED = 'FIREBASE_LOADED';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
